item {
    name: "bicycle",
    id: 1,
    display_name: "bicycle"
}
item {
    name: "bird",
    id: 2,
    display_name: "bird"
}
item {
    name: "cow",
    id: 3,
    display_name: "cow"
}
item {
    name: "dog",
    id: 4,
    display_name: "dog"
}
item {
    name: "giraffe",
    id: 5,
    display_name: "giraffe"
}
item {
    name: "horse",
    id: 6,
    display_name: "horse"
}
item {
    name: "kite",
    id: 7,
    display_name: "kite"
}
item {
    name: "person",
    id: 8,
    display_name: "person"
}
item {
    name: "pottedplant",
    id: 9,
    display_name: "pottedplant"
}
item {
    name: "truck",
    id: 10,
    display_name: "truck"
}
item {
    name: "zebra",
    id: 11,
    display_name: "zebra"
}
